project:
  base-dir: file:///C:\Users\xxx\Documents\proto\SpringAngular

#password:
#  salt: ee95a6FZ5sd8

server:
  port: 8080
  contextPath: /SpringAngular

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/spring-jwt?useSSL=false
    username: spring-jwt
    password: user

  resources:
    static-locations: ${project.base-dir}/src/main/resources/static/
    cache-period: 0

#TRACE-DEBUG-INFO-WARN-ERROR
logging:
  file: logs/dev_app.log
  pattern:
#    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    me.robnette.spring_angular: INFO
    org.springframework.web: WARN
    org.hibernate: WARN